spring:

  thymeleaf:
    prefix: classpath:/templates/

server:
  port: 8083
  mvc:
    view:
      suffix: .html

  application:
    name: FINAL


logging:
  level:
    org:
      hibernate:
        type:
          descriptor.sql: trace
