spring:
  datasource: #항상 여기 주석 처리 해야 함
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database.cp0mag4s6790.us-east-2.rds.amazonaws.com:3306/databasefortravel?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 123456789
  thymeleaf:
    prefix: classpath:/templates/
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl:
          auto: create
    database-platform: org.hibernate.dialect.MYSQL8Dialect


server:
  port: 8085
  mvc:
    view:
      suffix: .html

  application:
    name: sos

logging:
  level:
    org:
      hibernate:
        type:
          descriptor.sql: trace
