spring:
  application:
    name: smartFarm
  mvc:
    view:
      suffix: .html

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.100:1521:xe
    username: c##smart
    password: 1

server:
  port: 8090